<nav class="navbar">
  <div class="navbar-inner">
  	<a class="brand" href="#">Toolkit9000</a>
    <ul class="nav">
    	<li>
        <a href="<?php echo $this->url(array('module' => 'Index', 'controller'=>'Index','action'=>'index'), null, FALSE); ?>">Frontoffice</a>
      </li>
    	<li>
        <a href="<?php echo $this->url(array('module' => 'backoffice','controller'=>'admin','action'=>'index'), null, FALSE); ?>">Backoffice</a>
      </li>
    </ul>
  </div>
</nav>