<?php
/******************************************************************************
 *                                                                            *
 *                                                                            *
 *                                                                            *
 *                        aaaAAaaa            HHHHHH                          *
 *                     aaAAAAAAAAAAaa         HHHHHH                          *
 *                    aAAAAAAAAAAAAAAa        HHHHHH                          *
 *                   aAAAAAAAAAAAAAAAAa       HHHHHH                          *
 *                   aAAAAAa    aAAAAAA                                       *
 *                   AAAAAa      AAAAAA                                       *
 *                   AAAAAa      AAAAAA                                       *
 *                   aAAAAAa     AAAAAA                                       *
 *                    aAAAAAAaaaaAAAAAA       HHHHHH                          *
 *                     aAAAAAAAAAAAAAAA       HHHHHH                          *
 *                      aAAAAAAAAAAAAAA       HHHHHH                          *
 *                         aaAAAAAAAAAA       HHHHHH                          *
 *                                                                            *
 *                                                                            *
 *                                                                            *
 *      a r t e v e l d e  u n i v e r s i t y  c o l l e g e  g h e n t      *
 *                                                                            *
 *                                                                            *
 *                                 MEMBER OF GHENT UNIVERITY ASSOCIATION      *
 *                                                                            *
 *                                                                            *
 ******************************************************************************
 *
 * @author     Olivier Parent
 * @copyright  Copyright (c) 2012 Artevelde University College Ghent
 *
 * Improved by Group 10: Van de Calseyde Louis & Van der Eecken Pierre
 */
?>
<?php echo $this->navigation()->menu(); ?>
<?php echo $this->navigation()->breadcrumbs(); ?>
<h1><?php echo $this->title; ?></h1>
<?php //var_dump($this->userInfo); ?>
<dl class="dl-horizontal">
  <dt>Username:</dt>
  <dd><?= $this->userInfo['username']; ?></dd>
</dl>
<dl class="dl-horizontal">
  <dt>Given name:</dt>
  <dd><?= $this->userInfo['givenname']; ?></dd>
</dl>
<dl class="dl-horizontal">
  <dt>Family name:</dt>
  <dd><?= $this->userInfo['familyname']; ?></dd>
</dl>
<dl class="dl-horizontal">
  <dt>Email address:</dt>
  <dd><?= $this->userInfo['email']; ?></dd>
</dl>
<dl class="dl-horizontal">
  <dt>User role:</dt>
  <dd><?= $this->userRole['role']; ?></dd>
</dl>

<?php if (count($this->messages)) : ?>
  <?php foreach ($this->messages as $message) : ?>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>Succes!</strong> <?php echo $this->escape($message); ?>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
